# Site
name: "Akawnting"
title: "Akawnting"
description: "An educational website for accountants and business people."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: 'UA-141716897-1'
disqus: 'akawnting'
mailchimp-list: 'https://gmail.us3.list-manage.com/subscribe/post?u=44fa985ed01f97647e92edccf&amp;id=70a1215ec9'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  akawnting:
    name: Akawnting
    display_name: Akawnting
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: akawnting.com@gmail.com
    web: https://akawnting.com
    twitter: 
    description: "Akawnting is an educational endeavor which aims to help aspiring students reach their dreams."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
