# Site
name: "Akawnting"
title: "Akawnting"
description: "An educational website for accountants and business people."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  akawnting:
    name: Akawnting
    display_name: Akawnting
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: akawnting.com@gmail.com
    web: https://akawnting.com
    twitter: https://twitter.com/wowthemesnet
    description: "Akawnting is an educational endeavor which aims to help aspiring students reach their dreams. Our mission is to provide valuable enhancement to formal education by creating online contents and resources. This way, student learning is not limited to the four walls of the classroom. We, having CPA founders, initially plan to create accounting courses to show appreciation and gratitude towards the field. However, we envision to be a leader in online education which expands beyond accounting and business."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
